### ISSUE TITLE
[REQUEST] 支持插件启用禁用重载卸载等操作

### ISSUE THREAD

**Issue by zhzhongshi** [super1207/MiraiCQ#13]
![%~T0 `4`F8Y6{%N4{EZ@1HR](https://user-images.githubusercontent.com/39423408/153694855-746f9b56-7902-469f-a178-485b896fb177.png)
 求支持插件的启用禁用重载卸载等操作
![Y}MLJQ~7BB G}YNUF%N2)SR](https://user-images.githubusercontent.com/39423408/153694927-5e5b2b49-a80e-4c2c-bdd2-a9d41b7189a7.png)

**Comment by super1207** [comment]
已经支持。（以另一种方式

![QQ截图20220212210425](https://user-images.githubusercontent.com/30586004/153712653-1357858d-fb22-4f21-b96e-a01ae078cc02.png)
![QQ截图20220212210451](https://user-images.githubusercontent.com/30586004/153712657-527f8f1c-1d11-4af1-8a15-d864fbf0b9fc.png)


https://github.com/super1207/MiraiCQ/commit/6725c53681de9a40b4f06c5ffc9c3997a3acf008
