### ISSUE TITLE
从2.3.3更新到2.3.8(最新版)后，出现了线程过多导致MiraiCQ假死的问题

### ISSUE THREAD

**Issue by byx2020** [super1207/MiraiCQ#16]
此问题的表现形式为，启动并运行最新版(2.3.8)MiraiCQ一段时间后，就会出现如下图所示的情况，同时MiraiCQ无法处理和回复任何消息，需要通过手动重启MiraiCQ方能在恢复正常，不过时间一长仍然会出现如下图所示的情况。
需要说明的一点是，此问题在旧版(2.3.3)MiraiCQ上并没有出现(旧版连续运行几周都没有这个问题)，同时，出现此问题的MiraiCQ安装有“铃心自定义”和“水银词云机”这两个插件(见下图)，因此个人认为此问题可能与新版MiraiCQ增加的某个新特性和“铃心自定义”插件有关，但由于问题的出现具有一定的随机性，最近暂时没有时间进行详细排查，所以选择先退回了旧版(2.3.3)进行使用。
以下为插件运行环境信息：
服务器配置：4C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
go-cqhttp版本：1.0.0-rc2
MiraiCQ版本：2.3.8
其他说明：如果大佬需要更多信息或协助，也可以让我进行提供
    
![image](https://user-images.githubusercontent.com/58938653/173574754-bd4af7c5-29a2-4c1d-b014-0a2eafb53836.png)
![image](https://user-images.githubusercontent.com/58938653/173576276-20f99314-490c-4187-97e0-5423f5bbe14b.png)

**Comment by super1207** [comment]
这应该是一个过滤器的bug导致的，在发送图片时可能会出现，删除这三行应该就行了。
![TT%4JCRTSZ 1{Y7KM@P)(XA](https://user-images.githubusercontent.com/30586004/174259237-b8ff7234-36a3-4ebd-8eae-cc17d802a524.png)
下个版本解决。

**Comment by tjsky** [comment]
刚遇到这个问题，上来看看就看到了这一条。
按照上述解决方案，经过测试可以正常工作。

**Comment by byx2020** [comment]
> 这应该是一个过滤器的bug导致的，在发送图片时可能会出现，删除这三行应该就行了。 ![TT%4JCRTSZ 1{Y7KM@P)(XA](https://user-images.githubusercontent.com/30586004/174259237-b8ff7234-36a3-4ebd-8eae-cc17d802a524.png) 下个版本解决。

好的，非常感谢。

**Comment by super1207** [comment]
2.3.9 已修复
