### ISSUE TITLE
更新到2.3.8之后的另一个问题，部分插件功能失效

### ISSUE THREAD

**Issue by byx2020** [super1207/MiraiCQ#17]
此问题的表现形式为，在旧版(2.3.3及之前版本)MiraiCQ上已经正常使用了半年多的报更插件，在MiraiCQ更新到新版后，可以正常加载并启动，日志里面看也没有问题(可以正常启用或停用插件)，但是实际上功能是失效的(插件本身应该写出的小说log文件没有写出)，而且奇怪的是，在我升级之后，即便是把框架回退到原来的版本，插件还是不能用了，这一点非常费解，因为我确定版本和之前能用的时候是明明一模一样的，但实际结果就是不行，也不知道问题在哪里，之后我还去联系了插件开发者进行沟通，并进行了多次测试，不过还是没能找到问题的原因。
在获得插件开发者的同意之后，我把此插件及其相关配置文件放在了附件压缩包内，另外附上此插件的开源项目地址：[BGTZ：起点小说报更自动发群消息](https://gitee.com/Tian2Tian/bgtz) ，大佬如果有时间的话，可以帮忙看一下，不胜感激。
以下为插件运行环境信息：
服务器配置：4C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
go-cqhttp版本：1.0.0-rc3
MiraiCQ版本：2.3.8
其他说明：如果大佬需要更多信息或协助，也可以让我进行提供
![image](https://user-images.githubusercontent.com/58938653/176856070-2b4cea68-7809-4669-b392-c2f4c3a0b645.png)
插件及其相关配置文件(注意此插件的配置文件在data文件夹内，比较特殊)：[MiraiCQ-BGTZ.zip](https://github.com/super1207/MiraiCQ/files/9027523/MiraiCQ.zip)

**Comment by super1207** [comment]
如果退回2.3.3也不行的话，可能有其他原因，再观察下吧
我这段时间毕竟忙，过段时间再看看。

**Comment by byx2020** [comment]
> 如果退回2.3.3也不行的话，可能有其他原因，再观察下吧 我这段时间毕竟忙，过段时间再看看。

@super1207 感谢回复，不过我刚刚和插件作者继续沟通了一下，发现问题好像是出在起点小说网那边，既不是插件也不是MiraiCQ或gcq的问题，而是因为服务端的接口变了才导致功能失效的，非常抱歉打扰大佬了，这个issue我就关了吧
![image](https://user-images.githubusercontent.com/58938653/177064914-d3e9aea0-ae24-4032-9e60-9c82df8101ec.png)
