### ISSUE TITLE
铃心自定义Unicode转码显示问题

### ISSUE THREAD

**Issue by MuuuShin** [super1207/MiraiCQ#20]
环境：
windows server 2012R2
cqhttp 1.0.0 rc4
miraiCQ 2.4.1

可以正常使用Unicode的bot2号的配置：
MCL1.0.5
mirai-console 2.13.0（我是从8一路用上来的，都没出啥问题）

如题。之前也在qq群向您反馈过（
具体描述：
使用gbk字符集中已存在的unicode编码，可行，正常显示；

```
[Unicode=\u64]
```
机器人正常输出结果：
![image](https://user-images.githubusercontent.com/97760035/218810241-e3624107-2051-4690-af14-ad48161d10d2.png)

使用gbk字符集中不存在的unicode编码，无法正常显示，一个unicode字符替换为`??`（但是存在的部分还是正常显示的）
例2，特殊字符 ͟͝͞Ⅱ́̕：
```
[Unicode=&#32;&#863;&#861;&#862;&#8545;&#769;&#789;]
```

机器人输出结果：
![image](https://user-images.githubusercontent.com/97760035/218810918-e62dee0e-2a28-4c1d-8702-21325537c991.png)

选择开启以前的旧框架（MCL直接启动mirai）：
![image](https://user-images.githubusercontent.com/97760035/218812119-e04bb673-570f-4c6d-8ccd-35ae086dd748.png)

*尝试切换utf8编码未果。`chcp 65001`

不清楚到底是cqhttp导致最终转义失败还是miraiCQ，总之先把issue投一份在这里（

**Comment by super1207** [comment]
Unicode应该是mirai-native自己的拓展功能，以前的酷Q是没有的。
