### ISSUE TITLE
对接到Lagrange.Core时消息回复不及时

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [super1207/MiraiCQ#32]
如图，当对接[Lagrange.Core](https://github.com/LagrangeDev/Lagrange.Core)时，消息回复没有go-cqhttp那么及时
![Image_1698563075974.jpg](https://github.com/super1207/MiraiCQ/assets/86163024/7ea2529d-b001-4b1a-9b7b-9990f9741b21)

**Comment by super1207** [comment]
https://github.com/LagrangeDev/Lagrange.Core/commit/9c31d2ebff9bb538d3d372f350645e3362b88dd5
可能已经解决，试试
